export const SITE_STRINGS = {
  pl: {
    title: "Kalkulator kosztu przejazdu – Tankful",
    description: "Policz koszt paliwa na trasę po aktualnych cenach w Polsce i krajach UE – także przez kilka krajów, dla auta elektrycznego i na osobę.",
    heading: "Ile kosztuje paliwo na tę trasę?",
    lead: "Wpisz, skąd i dokąd jedziesz. Liczymy po aktualnych średnich cenach w Polsce i krajach UE, także na trasach przez kilka krajów.",
    from: "Skąd",
    to: "Dokąd",
    fromPlaceholder: "Wybierz miejsce startu",
    toPlaceholder: "Wybierz cel podróży",
    searchPlaceholder: "Wpisz miasto lub adres…",
    searching: "Szukam…",
    swap: "Zamień start i cel",
    variants: "Warianty trasy",
    fastest: "najszybsza",
    variant: "Trasa $1",
    viaPlaceholder: "Wybierz przystanek",
    addStop: "Dodaj cel",
    reorder: "Przeciągnij, aby zmienić kolejność",
    removeStop: "Usuń punkt trasy",
    stop: "Punkt trasy $1",
    theme: "Motyw",
    themeSystem: "System",
    themeLight: "Jasny",
    themeDark: "Ciemny",
    passengers: "Osób w aucie",
    ownPrice: "Własna cena za litr",
    ownPriceHint: "puste = średnia",
    currency: "Waluta",
    roundTrip: "Tam i z powrotem",
    working: "Liczę trasę…",
    placeholder: "Wybierz start i cel, a tu pojawi się koszt paliwa z podziałem na kraje.",
    errorRoute: "Nie da się wyznaczyć trasy samochodowej między tymi miejscami.",
    errorNetwork: "Serwis tras nie odpowiada. Spróbuj ponownie za chwilę.",
    errorPrices: "Nie udało się wczytać aktualnych cen – liczymy z ceną ręczną.",
    noResults: "Brak podpowiedzi",
    resultLabel: "Paliwo na trasę",
    perPerson: "$1 × $2 na osobę",
    roundTripCost: "tam i z powrotem: $1",
    countries: "Kraje na trasie",
    priceUsed: "Cena: $1",
    copyLink: "Kopiuj link do wyniku",
    copied: "Skopiowano link",
    copyFailed: "Zaznacz adres w pasku przeglądarki i skopiuj go ręcznie.",
    note: "To szacunek: realny koszt zależy od stylu jazdy, korków i tego, gdzie zatankujesz.",
    ctaHeading: "Chcesz to widzieć od razu w Google Maps?",
    ctaText: "Tankful to darmowa wtyczka do Chrome. Koszt paliwa pojawia się przy każdej trasie samochodowej w Mapach Google, bez przepisywania adresów.",
    ctaButton: "Dodaj do Chrome",
    sources: "Ceny: autocentrum.pl (Polska i województwa), biuletyn naftowy Komisji Europejskiej (kraje UE), kursy walut NBP. Trasy: OSRM, wyszukiwanie miejsc: Photon, oba na danych © OpenStreetMap.",
    updated: "Ceny zaktualizowane $1.",
    privacy: "Wpisane miejsca trafiają do serwisów wyszukiwania i wyznaczania tras. Nie zapisujemy ich ani nie używamy plików cookie. Liczymy anonimowe statystyki odwiedzin (GoatCounter) – bez wpisanych miejsc.",
    privacyLink: "Polityka prywatności wtyczki",
    code: "Kod źródłowy",
    hours: "$1 h $2 min",
    minutes: "$1 min",
    aboutButton: "Jak to działa?",
    aboutTitle: "Policz, ile wydasz na paliwo",
    aboutLead: "Darmowy kalkulator kosztu przejazdu samochodem. Bez rejestracji i bez szukania cen – aktualne ceny wczytujemy sami.",
    aboutStep1Title: "Wybierz trasę",
    aboutStep1: "Wpisz, skąd i dokąd jedziesz, i w razie potrzeby dodaj przystanki. Trasa pojawi się na mapie, często w kilku wariantach.",
    aboutStep2Title: "Opisz auto",
    aboutStep2: "Wybierz paliwo i średnie spalanie. Możesz podać liczbę osób, żeby podzielić koszt, i policzyć drogę tam i z powrotem.",
    aboutStep3Title: "Jak liczymy",
    aboutStep3: "Dystans × spalanie × cena. W Polsce bierzemy średnią cenę z województwa startu, w innych krajach UE – średnią krajową z biuletynu Komisji Europejskiej. Na trasie przez kilka krajów cenę ważymy kilometrami w każdym z nich.",
    aboutNote: "To szacunek – realny koszt zależy od stylu jazdy, korków i stacji. Wynikiem możesz podzielić się linkiem.",
    aboutStart: "Zaczynam",
  },
  en: {
    title: "Trip fuel cost calculator – Tankful",
    description: "Work out the fuel cost of a trip with current average prices in Poland and the EU – across borders, for electric cars and per person.",
    heading: "What will the fuel cost for this trip?",
    lead: "Enter where you start and where you are going. We use current average prices in Poland and the EU, including routes through several countries.",
    from: "From",
    to: "To",
    fromPlaceholder: "Choose where you start",
    toPlaceholder: "Choose your destination",
    searchPlaceholder: "Type a city or address…",
    searching: "Searching…",
    swap: "Swap start and destination",
    variants: "Route options",
    fastest: "fastest",
    variant: "Route $1",
    viaPlaceholder: "Choose a stop",
    addStop: "Add destination",
    reorder: "Drag to reorder",
    removeStop: "Remove this stop",
    stop: "Route point $1",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    passengers: "People in the car",
    ownPrice: "Your own price per litre",
    ownPriceHint: "empty = average",
    currency: "Currency",
    roundTrip: "Return trip",
    working: "Finding the route…",
    placeholder: "Choose a start and a destination and the fuel cost will appear here, split by country.",
    errorRoute: "There is no driving route between these places.",
    errorNetwork: "The routing service isn't responding. Try again in a moment.",
    errorPrices: "Current prices couldn't be loaded – using a manual price.",
    noResults: "No suggestions",
    resultLabel: "Fuel for the trip",
    perPerson: "$1 × $2 per person",
    roundTripCost: "return trip: $1",
    countries: "Countries on the route",
    priceUsed: "Price: $1",
    copyLink: "Copy link to this result",
    copied: "Link copied",
    copyFailed: "Select the address in the browser bar and copy it yourself.",
    note: "This is an estimate: the real cost depends on your driving, traffic and where you fill up.",
    ctaHeading: "Want to see this right in Google Maps?",
    ctaText: "Tankful is a free Chrome extension. The fuel cost shows up next to every driving route in Google Maps, with no retyping.",
    ctaButton: "Add to Chrome",
    sources: "Prices: autocentrum.pl (Poland and its regions), European Commission Weekly Oil Bulletin (EU countries), NBP exchange rates. Routes: OSRM, place search: Photon, both on © OpenStreetMap data.",
    updated: "Prices updated $1.",
    privacy: "The places you enter are sent to the search and routing services. We don't store them and we don't use cookies. We count anonymous visit statistics (GoatCounter), without the places you enter.",
    privacyLink: "Extension privacy policy",
    code: "Source code",
    hours: "$1 h $2 min",
    minutes: "$1 min",
    aboutButton: "How it works",
    aboutTitle: "Work out what you'll spend on fuel",
    aboutLead: "A free trip fuel cost calculator. No sign-up and no hunting for prices – we load current prices for you.",
    aboutStep1Title: "Choose your route",
    aboutStep1: "Enter where you start and where you're going, and add stops if you need them. The route appears on the map, often with a few options.",
    aboutStep2Title: "Describe your car",
    aboutStep2: "Pick the fuel and average consumption. You can add the number of people to split the cost, and count the return trip.",
    aboutStep3Title: "How we calculate",
    aboutStep3: "Distance × consumption × price. In Poland we use the average price in the region you start from; in other EU countries, the national average from the European Commission's Oil Bulletin. On routes through several countries, the price is weighted by the kilometres in each.",
    aboutNote: "This is an estimate – the real cost depends on your driving, traffic and where you fill up. You can share the result as a link.",
    aboutStart: "Let's go",
  },
};

type Key = keyof (typeof SITE_STRINGS)["pl"]

export function T(key: Key, ...subs: unknown[]): string {
  const strings = SITE_STRINGS[MAPKA_LOCALE === "pl" ? "pl" : "en"]
  return strings[key].replace(/\$(\d)/g, (_, n) => String(subs[n - 1] ?? ""))
}
