export const SITE_STRINGS = {
  pl: {
    title: "Kalkulator paliwa – koszt paliwa na trasę | Tankful",
    description: "Kalkulator kosztów paliwa: policz koszt paliwa na trasę ze spalaniem swojego auta, po aktualnych cenach w Polsce, UE, Wielkiej Brytanii i USA – też przez kilka krajów, dla elektryka i na osobę.",
    heading: "Kalkulator paliwa – ile kosztuje paliwo na tę trasę?",
    lead: "Wpisz, skąd i dokąd jedziesz, a policzymy koszt przejazdu samochodem po aktualnych średnich cenach paliw w Polsce, krajach UE, Wielkiej Brytanii i USA – także na trasach przez kilka krajów i w przeliczeniu na osobę.",
    from: "Skąd",
    to: "Dokąd",
    fromPlaceholder: "Wybierz miejsce startu",
    toPlaceholder: "Wybierz cel podróży",
    searchPlaceholder: "Wpisz miasto lub adres…",
    searching: "Szukam…",
    swap: "Zamień start i cel",
    variants: "Warianty trasy",
    fastest: "najszybsza",
    variant: "Trasa $1",
    viaPlaceholder: "Wybierz przystanek",
    addStop: "Dodaj cel",
    reorder: "Przeciągnij, aby zmienić kolejność",
    removeStop: "Usuń punkt trasy",
    stop: "Punkt trasy $1",
    theme: "Motyw",
    themeSystem: "System",
    themeLight: "Jasny",
    themeDark: "Ciemny",
    passengers: "Osób w aucie",
    ownPrice: "Własna cena za litr",
    ownPriceUs: "Własna cena za galon",
    ownPriceHint: "średnia",
    currency: "Waluta",
    roundTrip: "Tam i z powrotem",
    working: "Liczę trasę…",
    placeholder: "Wybierz start i cel, a tu pojawi się koszt paliwa z podziałem na kraje.",
    errorRoute: "Nie da się wyznaczyć trasy samochodowej między tymi miejscami.",
    errorNetwork: "Serwis tras nie odpowiada. Spróbuj ponownie za chwilę.",
    errorPrices: "Nie udało się wczytać aktualnych cen – liczymy z ceną ręczną.",
    noResults: "Brak podpowiedzi",
    resultLabel: "Paliwo na trasę",
    perPerson: "$1 × $2 na osobę",
    roundTripCost: "tam i z powrotem: $1",
    countries: "Kraje na trasie",
    priceUsed: "Cena: $1",
    copyLink: "Kopiuj link do wyniku",
    copied: "Skopiowano link",
    copyFailed: "Zaznacz adres w pasku przeglądarki i skopiuj go ręcznie.",
    note: "To szacunek: realny koszt zależy od stylu jazdy, korków i tego, gdzie zatankujesz.",
    ctaHeading: "Chcesz to widzieć od razu w Google Maps?",
    ctaText: "Tankful to darmowa wtyczka do Chrome. Koszt paliwa pojawia się przy każdej trasie samochodowej w Mapach Google, bez przepisywania adresów.",
    ctaButton: "Dodaj do Chrome",
    installHeading: "Tankful na ekranie głównym",
    installText: "Dodaj kalkulator do ekranu głównego telefonu i otwieraj go jednym stuknięciem, jak aplikację. Za darmo, bez sklepu z aplikacjami.",
    installButton: "Dodaj do ekranu głównego",
    installIos: "Stuknij „Udostępnij” (w Safari na dole ekranu, w Chrome w pasku adresu), a potem „Do ekranu początkowego”.",
    installAndroid: "Otwórz menu przeglądarki (⋮) i wybierz „Dodaj do ekranu głównego” albo „Zainstaluj aplikację”.",
    installInApp: "Najpierw otwórz tę stronę w przeglądarce (menu ⋯ → „Otwórz w przeglądarce”), a potem dodaj ją do ekranu głównego.",
    sources: "Ceny: biuletyn naftowy Komisji Europejskiej (Polska i kraje UE), w Polsce korygowany przy dużych zmianach cen hurtowych Orlenu, cotygodniowe ceny rządu Wielkiej Brytanii (GOV.UK, Open Government Licence), cotygodniowe ceny amerykańskiej agencji EIA (U.S. Energy Information Administration), kursy walut NBP. Trasy: OSRM, wyszukiwanie miejsc: Photon, oba na danych © OpenStreetMap.",
    updated: "Ceny zaktualizowane $1.",
    privacy: "Wpisane miejsca trafiają do serwisów wyszukiwania i wyznaczania tras. Nie zapisujemy ich ani nie używamy plików cookie. Liczymy anonimowe statystyki odwiedzin (GoatCounter) – bez wpisanych miejsc.",
    privacyLink: "Polityka prywatności wtyczki",
    code: "Kod źródłowy",
    hours: "$1 h $2 min",
    minutes: "$1 min",
    aboutButton: "Jak to działa?",
    aboutTitle: "Policz, ile wydasz na paliwo",
    aboutLead: "Darmowy kalkulator kosztu przejazdu samochodem. Bez rejestracji i bez szukania cen – aktualne ceny wczytujemy sami.",
    aboutStep1Title: "Wybierz trasę",
    aboutStep1: "Wpisz, skąd i dokąd jedziesz, i w razie potrzeby dodaj przystanki. Trasa pojawi się na mapie, często w kilku wariantach.",
    aboutStep2Title: "Opisz auto",
    aboutStep2: "Wybierz paliwo i średnie spalanie. Możesz podać liczbę osób, żeby podzielić koszt, i policzyć drogę tam i z powrotem.",
    aboutStep3Title: "Jak liczymy",
    aboutStep3: "Dystans × spalanie × cena. W Polsce i innych krajach UE bierzemy średnią krajową z biuletynu Komisji Europejskiej, w Wielkiej Brytanii – z cotygodniowych danych rządu brytyjskiego, w USA – z cotygodniowych cen agencji EIA dla stanu albo regionu. Na trasie przez kilka krajów cenę ważymy kilometrami w każdym z nich.",
    aboutNote: "To szacunek – realny koszt zależy od stylu jazdy, korków i stacji. Wynikiem możesz podzielić się linkiem.",
    aboutStart: "Zaczynam",
    faqHeading: "Najczęstsze pytania",
    faqTripQ: "Jak obliczyć koszt podróży samochodem?",
    faqTripA: "Najwięcej kosztuje paliwo: wpisz start i cel, a kalkulator policzy koszt paliwa na całej trasie po aktualnych cenach w każdym kraju po drodze, także tam i z powrotem i w przeliczeniu na osobę. Do kosztu podróży dolicz opłaty, których kalkulator nie zna: autostrady, winiety, parkingi i promy.",
    faq1q: "Jak obliczyć koszt paliwa na trasę?",
    faq1a: "Podziel dystans przez 100 i pomnóż przez spalanie oraz cenę za litr. Na przykład 300 km autem, które pali 7 l/100 km, to 21 litrów – przy cenie 6,50 zł za litr około 137 zł. Kalkulator robi to za Ciebie, z dystansem prawdziwej trasy i aktualną ceną.",
    faq2q: "Skąd biorą się ceny paliw?",
    faq2a: "To średnie krajowe z cotygodniowego biuletynu naftowego Komisji Europejskiej – w Polsce i w innych krajach UE – w Wielkiej Brytanii z cotygodniowych danych rządu brytyjskiego, a w USA z cotygodniowych cen agencji EIA – dla stanu, jeśli EIA go podaje, a w pozostałych stanach dla regionu. W Polsce, gdy ceny hurtowe Orlenu wyraźnie się zmienią od dnia biuletynu, korygujemy cenę o tę zmianę. To średnia – na stacjach w miastach i przy autostradach bywa drożej. Waluty przeliczamy po kursach NBP. Jeśli tankujesz taniej, wpisz własną cenę.",
    faq3q: "Jak liczony jest przejazd przez kilka krajów?",
    faq3a: "Sprawdzamy, ile kilometrów trasy wypada w każdym kraju, i ważymy cenę paliwa tymi kilometrami. Trasa Warszawa – Berlin liczy się więc częściowo po polskiej, a częściowo po niemieckiej cenie.",
    faq4q: "Ile kosztuje przejazd autem elektrycznym?",
    faq4a: "Wybierz „Elektryczny (EV)” i podaj zużycie w kWh na 100 km. Pokażemy przedział: od ładowania w domu do szybkich ładowarek przy trasie.",
    faq5q: "Jak podzielić koszt przejazdu między pasażerów?",
    faq5a: "Ustaw liczbę osób w aucie – obok kosztu całej trasy zobaczysz kwotę na osobę. Przyciskiem „Kopiuj link do wyniku” wyślesz wyliczenie znajomym, a oni zobaczą tę samą trasę i kwotę.",
    faq6q: "Czy koszt paliwa może się pokazywać od razu w Google Maps?",
    faq6a: "Tak – darmowa wtyczka Tankful do Chrome dopisuje koszt paliwa do każdej trasy samochodowej w Mapach Google, bez przepisywania adresów.",
    routeTitle: "Koszt przejazdu $1 – $2: benzyna, diesel, LPG i elektryk | Tankful",
    routeDescription: "Ile kosztuje paliwo na trasie $1 – $2 ($3 km)? Koszt benzyny, diesla, LPG i ładowania auta elektrycznego po aktualnych cenach, tam i z powrotem i na osobę.",
    routeHeading: "Koszt przejazdu $1 – $2",
    routeLead: "Policz koszt paliwa na trasie $1 – $2 dla swojego auta. Możesz zmienić start i cel, dodać przystanki i podzielić koszt na osoby.",
    routeTableHeading: "Ile kosztuje paliwo na trasie $1 – $2?",
    routeSummary: "Najszybsza trasa $1 – $2 ma ok. $3 km, a jazda bez korków zajmuje ok. $4.",
    routeCountries: "Po drodze: $1.",
    routeFuel: "Paliwo",
    routeOneWay: "W jedną stronę",
    routeReturn: "Tam i z powrotem",
    routePerPerson: "Na osobę (4 os.)",
    routeAssumption: "Wyliczenie dla najszybszej trasy i typowego spalania. Swoje spalanie, liczbę osób i warianty trasy ustawisz w kalkulatorze.",
    popularRoutes: "Popularne trasy",
    guidesHeading: "Poradniki",
    guidesLink: "Ceny paliw w Europie, tankowanie przed granicą, koszt 100 km i inne poradniki",
    language: "Język",
    ferry: "prom lub pociąg $1, bez paliwa",
  },
  en: {
    title: "Fuel cost calculator – trip fuel cost by route | Tankful",
    description: "Fuel cost calculator: work out the fuel cost of a trip from your car's consumption and current average prices in Poland, the EU, the UK and the US – across borders, for electric cars and per person.",
    heading: "Fuel cost calculator – what will this trip cost?",
    lead: "Enter where you start and where you are going. We use current average prices in Poland, the EU, the UK and the US, including routes through several countries.",
    from: "From",
    to: "To",
    fromPlaceholder: "Choose where you start",
    toPlaceholder: "Choose your destination",
    searchPlaceholder: "Type a city or address…",
    searching: "Searching…",
    swap: "Swap start and destination",
    variants: "Route options",
    fastest: "fastest",
    variant: "Route $1",
    viaPlaceholder: "Choose a stop",
    addStop: "Add destination",
    reorder: "Drag to reorder",
    removeStop: "Remove this stop",
    stop: "Route point $1",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    passengers: "People in the car",
    ownPrice: "Your own price per litre",
    ownPriceUs: "Your own price per gallon",
    ownPriceHint: "average",
    currency: "Currency",
    roundTrip: "Return trip",
    working: "Finding the route…",
    placeholder: "Choose a start and a destination and the fuel cost will appear here, split by country.",
    errorRoute: "There is no driving route between these places.",
    errorNetwork: "The routing service isn't responding. Try again in a moment.",
    errorPrices: "Current prices couldn't be loaded – using a manual price.",
    noResults: "No suggestions",
    resultLabel: "Fuel for the trip",
    perPerson: "$1 × $2 per person",
    roundTripCost: "return trip: $1",
    countries: "Countries on the route",
    priceUsed: "Price: $1",
    copyLink: "Copy link to this result",
    copied: "Link copied",
    copyFailed: "Select the address in the browser bar and copy it yourself.",
    note: "This is an estimate: the real cost depends on your driving, traffic and where you fill up.",
    ctaHeading: "Want to see this right in Google Maps?",
    ctaText: "Tankful is a free Chrome extension. The fuel cost shows up next to every driving route in Google Maps, with no retyping.",
    ctaButton: "Add to Chrome",
    installHeading: "Tankful on your home screen",
    installText: "Add the calculator to your phone's home screen and open it with one tap, like an app. Free, no app store needed.",
    installButton: "Add to home screen",
    installIos: "Tap “Share” (at the bottom in Safari, in the address bar in Chrome), then “Add to Home Screen”.",
    installAndroid: "Open the browser menu (⋮) and choose “Add to Home screen” or “Install app”.",
    installInApp: "First open this page in your browser (menu ⋯ → “Open in browser”), then add it to your home screen.",
    sources: "Prices: European Commission Weekly Oil Bulletin (Poland and EU countries), adjusted in Poland when Orlen wholesale prices move significantly, UK government weekly road fuel prices (GOV.UK, Open Government Licence), U.S. Energy Information Administration weekly gasoline and diesel prices, NBP exchange rates. Routes: OSRM, place search: Photon, both on © OpenStreetMap data.",
    updated: "Prices updated $1.",
    privacy: "The places you enter are sent to the search and routing services. We don't store them and we don't use cookies. We count anonymous visit statistics (GoatCounter), without the places you enter.",
    privacyLink: "Extension privacy policy",
    code: "Source code",
    hours: "$1 h $2 min",
    minutes: "$1 min",
    aboutButton: "How it works",
    aboutTitle: "Work out what you'll spend on fuel",
    aboutLead: "A free trip fuel cost calculator. No sign-up and no hunting for prices – we load current prices for you.",
    aboutStep1Title: "Choose your route",
    aboutStep1: "Enter where you start and where you're going, and add stops if you need them. The route appears on the map, often with a few options.",
    aboutStep2Title: "Describe your car",
    aboutStep2: "Pick the fuel and average consumption. You can add the number of people to split the cost, and count the return trip.",
    aboutStep3Title: "How we calculate",
    aboutStep3: "Distance × consumption × price. In Poland and other EU countries we use the national average from the European Commission's Oil Bulletin; in the UK, the UK government's weekly figures; in the US, the EIA's weekly price for the state or its region. On routes through several countries, the price is weighted by the kilometres in each.",
    aboutNote: "This is an estimate – the real cost depends on your driving, traffic and where you fill up. You can share the result as a link.",
    aboutStart: "Let's go",
    faqHeading: "Frequently asked questions",
    faqTripQ: "How do I work out the cost of a car trip?",
    faqTripA: "Fuel is the biggest part: enter the start and destination and the calculator works out the fuel cost for the whole route at current prices in every country on the way, including the return trip and the cost per person. Add the costs it doesn't know about: motorway tolls, vignettes, parking and ferries.",
    faq1q: "How do I work out the fuel cost of a trip?",
    faq1a: "Divide the distance by 100, then multiply by your consumption and the price per litre. For example, 300 km in a car that uses 7 l/100 km takes 21 litres – at €1.80 per litre that's about €38. The calculator does this for you, with the distance of the real route and a current price.",
    faq2q: "Where do the fuel prices come from?",
    faq2a: "National averages from the European Commission's Weekly Oil Bulletin for Poland and other EU countries, the UK government's weekly road fuel prices for the UK, and the U.S. Energy Information Administration's weekly prices for the US – for the state where the EIA publishes one, otherwise for its region. In Poland, when Orlen wholesale prices have clearly moved since the bulletin date, we adjust the price by that change. It's an average – city and motorway stations are often more expensive. Currencies are converted at National Bank of Poland rates. If you fill up for less, enter your own price.",
    faq3q: "How are trips through several countries calculated?",
    faq3a: "We work out how many kilometres of the route fall in each country and weight the fuel price by those kilometres. A trip from Warsaw to Berlin is costed partly at the Polish price and partly at the German one.",
    faq4q: "How much does a trip cost in an electric car?",
    faq4a: "Choose “Electric (EV)” and enter consumption in kWh per 100 km. You'll see a range, from charging at home to fast chargers along the way.",
    faq5q: "How do I split the fuel cost between passengers?",
    faq5a: "Set the number of people in the car – next to the cost of the whole trip you'll see the amount per person. Use “Copy link to this result” to send it to your friends; they'll see the same route and amount.",
    faq6q: "Can I see the fuel cost right in Google Maps?",
    faq6a: "Yes – the free Tankful extension for Chrome adds the fuel cost to every driving route in Google Maps, with no retyping.",
    routeTitle: "$1 to $2 fuel cost: petrol, diesel, LPG and EV | Tankful",
    routeDescription: "How much is the fuel from $1 to $2 ($3 km)? The cost of petrol, diesel, LPG and charging an electric car at current prices, return trip and per person.",
    routeHeading: "$1 to $2: trip fuel cost",
    routeLead: "Work out the fuel cost from $1 to $2 for your car. You can change the start and destination, add stops and split the cost between passengers.",
    routeTableHeading: "How much is the fuel from $1 to $2?",
    routeSummary: "The fastest route from $1 to $2 is about $3 km and takes about $4 without traffic.",
    routeCountries: "Countries on the way: $1.",
    routeFuel: "Fuel",
    routeOneWay: "One way",
    routeReturn: "Return trip",
    routePerPerson: "Per person (4 people)",
    routeAssumption: "Costed for the fastest route and typical consumption. Set your own consumption, passengers and route options in the calculator.",
    popularRoutes: "Popular routes",
    guidesHeading: "Guides",
    guidesLink: "Fuel prices in Europe, filling up before a border, the cost of 100 km and more guides",
    language: "Language",
    ferry: "ferry or train $1, no fuel",
  },
  de: {
    title: "Spritkostenrechner – Spritkosten für jede Strecke berechnen | Tankful",
    description: "Spritkostenrechner: Berechne die Spritkosten deiner Fahrt mit deinem Verbrauch und aktuellen Durchschnittspreisen in Deutschland, Polen, der EU, Großbritannien und den USA – auch über mehrere Länder, für E-Autos und pro Person.",
    heading: "Spritkostenrechner – was kostet der Sprit für diese Strecke?",
    lead: "Gib Start und Ziel ein. Wir rechnen mit aktuellen Durchschnittspreisen in Deutschland, Polen, der EU, Großbritannien und den USA – auch auf Strecken durch mehrere Länder.",
    from: "Von",
    to: "Nach",
    fromPlaceholder: "Startort wählen",
    toPlaceholder: "Ziel wählen",
    searchPlaceholder: "Stadt oder Adresse eingeben…",
    searching: "Suche…",
    swap: "Start und Ziel tauschen",
    variants: "Routenvarianten",
    fastest: "schnellste",
    variant: "Route $1",
    viaPlaceholder: "Zwischenstopp wählen",
    addStop: "Ziel hinzufügen",
    reorder: "Zum Sortieren ziehen",
    removeStop: "Routenpunkt entfernen",
    stop: "Routenpunkt $1",
    theme: "Design",
    themeSystem: "System",
    themeLight: "Hell",
    themeDark: "Dunkel",
    passengers: "Personen im Auto",
    ownPrice: "Eigener Preis pro Liter",
    ownPriceUs: "Eigener Preis pro Gallone",
    ownPriceHint: "Durchschnitt",
    currency: "Währung",
    roundTrip: "Hin und zurück",
    working: "Route wird berechnet…",
    placeholder: "Wähle Start und Ziel – hier erscheinen dann die Spritkosten, aufgeteilt nach Ländern.",
    errorRoute: "Zwischen diesen Orten gibt es keine Autoroute.",
    errorNetwork: "Der Routendienst antwortet nicht. Versuch es gleich noch einmal.",
    errorPrices: "Aktuelle Preise konnten nicht geladen werden – es gilt ein eigener Preis.",
    noResults: "Keine Vorschläge",
    resultLabel: "Sprit für die Strecke",
    perPerson: "$1 × $2 pro Person",
    roundTripCost: "hin und zurück: $1",
    countries: "Länder auf der Strecke",
    priceUsed: "Preis: $1",
    copyLink: "Link zum Ergebnis kopieren",
    copied: "Link kopiert",
    copyFailed: "Markiere die Adresse in der Adressleiste und kopiere sie selbst.",
    note: "Das ist eine Schätzung: Die echten Kosten hängen von Fahrweise, Verkehr und Tankstelle ab.",
    ctaHeading: "Die Spritkosten direkt in Google Maps sehen?",
    ctaText: "Tankful ist eine kostenlose Chrome-Erweiterung. Die Spritkosten erscheinen bei jeder Autoroute in Google Maps, ohne Adressen abzutippen.",
    ctaButton: "Zu Chrome hinzufügen",
    installHeading: "Tankful auf dem Startbildschirm",
    installText: "Leg den Rechner auf den Startbildschirm deines Handys und öffne ihn mit einem Tippen wie eine App. Kostenlos, ohne App-Store.",
    installButton: "Zum Startbildschirm hinzufügen",
    installIos: "Tippe auf „Teilen“ (in Safari unten, in Chrome in der Adressleiste) und dann auf „Zum Home-Bildschirm“.",
    installAndroid: "Öffne das Browsermenü (⋮) und wähle „Zum Startbildschirm hinzufügen“ oder „App installieren“.",
    installInApp: "Öffne diese Seite zuerst im Browser (Menü ⋯ → „Im Browser öffnen“) und füge sie dann zum Startbildschirm hinzu.",
    sources: "Preise: Weekly Oil Bulletin der Europäischen Kommission (Deutschland, Polen und die anderen EU-Länder), in Polen bei deutlichen Änderungen der Orlen-Großhandelspreise angepasst, wöchentliche Kraftstoffpreise der britischen Regierung (GOV.UK, Open Government Licence), wöchentliche Benzin- und Dieselpreise der U.S. Energy Information Administration, Wechselkurse der Polnischen Nationalbank (NBP). Routen: OSRM, Ortssuche: Photon, beide mit Daten © OpenStreetMap.",
    updated: "Preise aktualisiert am $1.",
    privacy: "Die eingegebenen Orte gehen an die Such- und Routendienste. Wir speichern sie nicht und verwenden keine Cookies. Wir zählen anonyme Besuchsstatistiken (GoatCounter) – ohne die eingegebenen Orte.",
    privacyLink: "Datenschutzerklärung der Erweiterung",
    code: "Quellcode",
    hours: "$1 Std. $2 Min.",
    minutes: "$1 Min.",
    aboutButton: "So funktioniert's",
    aboutTitle: "Berechne, was du für Sprit ausgibst",
    aboutLead: "Ein kostenloser Spritkostenrechner für Autofahrten. Ohne Anmeldung und ohne Preissuche – aktuelle Preise laden wir selbst.",
    aboutStep1Title: "Route wählen",
    aboutStep1: "Gib Start und Ziel ein und füge bei Bedarf Zwischenstopps hinzu. Die Route erscheint auf der Karte, oft in mehreren Varianten.",
    aboutStep2Title: "Auto beschreiben",
    aboutStep2: "Wähle Kraftstoff und Durchschnittsverbrauch. Du kannst die Zahl der Personen angeben, um die Kosten zu teilen, und die Rückfahrt mitrechnen.",
    aboutStep3Title: "So rechnen wir",
    aboutStep3: "Entfernung × Verbrauch × Preis. In Deutschland, Polen und den anderen EU-Ländern nehmen wir den Landesdurchschnitt aus dem Oil Bulletin der Europäischen Kommission, in Großbritannien die wöchentlichen Zahlen der britischen Regierung, in den USA die wöchentlichen Preise der EIA für den Bundesstaat oder die Region. Auf Strecken durch mehrere Länder gewichten wir den Preis mit den Kilometern in jedem Land.",
    aboutNote: "Das ist eine Schätzung – die echten Kosten hängen von Fahrweise, Verkehr und Tankstelle ab. Das Ergebnis kannst du als Link teilen.",
    aboutStart: "Los geht's",
    faqHeading: "Häufige Fragen",
    faqTripQ: "Wie berechne ich die Kosten einer Autofahrt?",
    faqTripA: "Der größte Posten ist der Sprit: Gib Start und Ziel ein, und der Rechner ermittelt die Spritkosten für die ganze Strecke mit aktuellen Preisen in jedem Land unterwegs – auch für Hin- und Rückfahrt und pro Person. Rechne die Kosten dazu, die er nicht kennt: Maut, Vignetten, Parken und Fähren.",
    faq1q: "Wie berechne ich die Spritkosten für eine Strecke?",
    faq1a: "Teile die Entfernung durch 100 und multipliziere mit dem Verbrauch und dem Literpreis. Beispiel: 300 km mit einem Auto, das 7 l/100 km braucht, sind 21 Liter – bei 1,80 € pro Liter etwa 38 €. Der Rechner erledigt das für dich, mit der Entfernung der echten Route und einem aktuellen Preis.",
    faq2q: "Woher kommen die Spritpreise?",
    faq2a: "Es sind Landesdurchschnitte aus dem wöchentlichen Oil Bulletin der Europäischen Kommission für Deutschland, Polen und die anderen EU-Länder, aus den wöchentlichen Zahlen der britischen Regierung für Großbritannien und aus den wöchentlichen Preisen der U.S. Energy Information Administration für die USA. In Polen passen wir den Preis an, wenn sich die Orlen-Großhandelspreise seit dem Bulletin deutlich verändert haben. Es ist ein Durchschnitt – an Autobahn- und Stadttankstellen ist es oft teurer. Währungen rechnen wir zu Kursen der Polnischen Nationalbank um. Wenn du günstiger tankst, gib deinen eigenen Preis ein.",
    faq3q: "Wie werden Fahrten durch mehrere Länder berechnet?",
    faq3a: "Wir ermitteln, wie viele Kilometer der Route in jedem Land liegen, und gewichten den Spritpreis mit diesen Kilometern. Eine Fahrt von Berlin nach Warschau wird also teils mit dem deutschen und teils mit dem polnischen Preis gerechnet.",
    faq4q: "Was kostet eine Fahrt mit dem E-Auto?",
    faq4a: "Wähle „Elektro (EV)“ und gib den Verbrauch in kWh pro 100 km ein. Du siehst eine Spanne – vom Laden zu Hause bis zum Schnelllader an der Strecke.",
    faq5q: "Wie teile ich die Spritkosten unter Mitfahrern auf?",
    faq5a: "Stell die Zahl der Personen im Auto ein – neben den Kosten der ganzen Fahrt siehst du den Betrag pro Person. Mit „Link zum Ergebnis kopieren“ schickst du die Rechnung an deine Mitfahrer, und sie sehen dieselbe Route und denselben Betrag.",
    faq6q: "Kann ich die Spritkosten direkt in Google Maps sehen?",
    faq6a: "Ja – die kostenlose Chrome-Erweiterung Tankful zeigt die Spritkosten bei jeder Autoroute in Google Maps, ohne Adressen abzutippen.",
    routeTitle: "Spritkosten $1 – $2: Benzin, Diesel, LPG und E-Auto | Tankful",
    routeDescription: "Was kostet der Sprit von $1 nach $2 ($3 km)? Kosten für Benzin, Diesel, LPG und das Laden eines E-Autos zu aktuellen Preisen, hin und zurück und pro Person.",
    routeHeading: "Spritkosten $1 – $2",
    routeLead: "Berechne die Spritkosten von $1 nach $2 für dein Auto. Du kannst Start und Ziel ändern, Zwischenstopps hinzufügen und die Kosten auf Mitfahrer aufteilen.",
    routeTableHeading: "Was kostet der Sprit von $1 nach $2?",
    routeSummary: "Die schnellste Route von $1 nach $2 ist etwa $3 km lang und dauert ohne Stau etwa $4.",
    routeCountries: "Unterwegs: $1.",
    routeFuel: "Kraftstoff",
    routeOneWay: "Einfache Fahrt",
    routeReturn: "Hin und zurück",
    routePerPerson: "Pro Person (4 Pers.)",
    routeAssumption: "Berechnet für die schnellste Route und einen typischen Verbrauch. Eigenen Verbrauch, Mitfahrer und Routenvarianten stellst du im Rechner ein.",
    popularRoutes: "Beliebte Strecken",
    guidesHeading: "Ratgeber",
    guidesLink: "Tanken in Polen, Spritpreise in Tschechien und Österreich und weitere Ratgeber",
    language: "Sprache",
    ferry: "Fähre oder Zug $1, ohne Sprit",
  },
};

type Key = keyof (typeof SITE_STRINGS)["pl"]

export function T(key: Key, ...subs: unknown[]): string {
  const strings = SITE_STRINGS[(MAPKA_LOCALE in SITE_STRINGS ? MAPKA_LOCALE : "en") as keyof typeof SITE_STRINGS]
  return strings[key].replace(/\$(\d)/g, (_, n) => String(subs[n - 1] ?? ""))
}
